export const fixtureBlocks = {
  '0': {
    'id': '0',
    'userId': '0',
    'stackId': '0',
    'task': 'Study for CSE11 midterm',
    'description': '',
    'durationWork': 25,
    'durationBreak': 5,
    'numBursts': 3,
    'createdAt': 'Fri, 17 Jul 2020 06:14:35 GMT',
  },

  '1': {
    'id': '1',
    'userId': '0',
    'stackId': '0',
    'task': 'Practice guitar',
    'description': 'Spend the first block rehearsing for the upcoming show.',
    'durationWork': 25,
    'durationBreak': 5,
    'numBursts': 2,
    'createdAt': 'Fri, 17 Jul 2020 06:15:35 GMT',
  },

  '2': {
    'id': '2',
    'userId': '0',
    'stackId': '0',
    'task': 'Read book',
    'description': 'Checkout Fyodor Dostoyevsky',
    'durationWork': 25,
    'durationBreak': 5,
    'numBursts': 2,
    'createdAt': 'Fri, 17 Jul 2020 06:18:35 GMT',
  },

  '3': {
    'id': '3',
    'userId': '0',
    'stackId': '1',
    'task': 'Planks',
    'description': '',
    'durationWork': 2,
    'durationBreak': 3,
    'numBursts': 3,
    'createdAt': 'Fri, 13 Jul 2020 06:14:35 GMT',
  },

  '4': {
    'id': '4',
    'userId': '0',
    'stackId': '1',
    'task': 'Squats',
    'description': '',
    'durationWork': 5,
    'durationBreak': 3,
    'numBursts': 4,
    'createdAt': 'Fri, 13 Jul 2020 06:15:35 GMT',
  },

  '5': {
    'id': '5',
    'userId': '0',
    'stackId': '1',
    'task': 'Cardio',
    'description': '4x100m sprints',
    'durationWork': 10,
    'durationBreak': 5,
    'numBursts': 4,
    'createdAt': 'Fri, 13 Jul 2020 06:18:35 GMT',
  },

  '6': {
    'id': '6',
    'userId': '0',
    'stackId': '2',
    'task': 'Study for biology',
    'description': 'Currently learning about the circulatory system',
    'durationWork': 45,
    'durationBreak': 10,
    'numBursts': 3,
    'createdAt': 'Fri, 15 Jul 2020 06:14:35 GMT',
  },

  '7': {
    'id': '7',
    'userId': '0',
    'stackId': '2',
    'task': 'Study for Econ',
    'description': 'Review what perfect competition is',
    'durationWork': 45,
    'durationBreak': 10,
    'numBursts': 4,
    'createdAt': 'Fri, 15 Jul 2020 06:15:35 GMT',
  },


  '8': {
    'id': '8',
    'userId': '0',
    'stackId': '2',
    'task': 'Study Latin vocab',
    'description': '',
    'durationWork': 15,
    'durationBreak': 5,
    'numBursts': 6,
    'createdAt': 'Fri, 15 Jul 2020 06:15:35 GMT',
  },
};
