export const theme = {
  primaryDark: '#242741',
  primaryDarkDull: '#C3C6DE',
  primaryLight: '#FFFFFF',
  primaryLightDull: '#F4F4F4',
  primaryLightHover: '#ECECEC',
  primaryLightSelected: '#E8E8E8',
  midtone: '#3C4271',
  secondary: '#4CD2B2',
  secondaryAlt: '#FF8541',
  boxShadow: 'rgba(0, 0, 0, 0.15)',
  landingInput: '#EEEEEE',
  greetingCaption: '#AAAAAA',
  greetingTitle: '#333333',
  errorMessage: '#DE3163',
};
