// session
export const SESSION_SET_AUTHENTICATED = 'SESSION_SET_AUTHENTICATED';
export const SESSION_LOADING_LANDING = 'SESSION_LOADING_LANDING';
export const SESSION_LOADING_BLOCKS = 'SESSION_LOADING_BLOCKS';
export const SESSION_LOADING_STACKS = 'SESSION_LOADING_STACKS';
export const SESSION_SET_USER = 'SESSION_SET_USER';
export const SESSION_CLEAR = 'SESSION_CLEAR';
export const SESSION_SET_DISPLAY = 'SESSION_SET_DISPLAY';
export const SESSION_ERRORS_SET = 'SESSION_ERRORS_SET';

// data
export const DATA_SET_STACKS = 'DATA_SET_STACKS';
export const DATA_SET_STACK = 'DATA_SET_STACK';
export const DATA_SET_BLOCKS = 'DATA_SET_BLOCKS';
export const DATA_SET_BLOCK = 'DATA_SET_BLOCK';
export const DATA_CLEAR = 'DATA_CLEAR';

// displayPlaylist
export const PLAYLIST_SET_MODE = 'PLAYLIST_SET_MODE';
export const PLAYLIST_SET_FOCUS_INITIAL = 'PLAYLIST_SET_FOCUS_INITIAL';
export const PLAYLIST_SET_FOCUS_FINISHED = 'PLAYLIST_SET_FOCUS_FINISHED';
export const PLAYLIST_SET_FOCUS_REMAINING = 'PLAYLIST_SET_FOCUS_REMAINING';
export const PLAYLIST_SET_FOCUS_CURRENT = 'PLAYLIST_SET_FOCUS_CURRENT';
export const PLAYLIST_ADD_COMPLETED_BLOCKS = 'PLAYLIST_ADD_COMPLETED_BLOCKS';
export const PLAYLIST_CLEAR_COMPLETED_BLOCKS =
  'PLAYLIST_CLEAR_COMPLETED_BLOCKS';
export const PLAYLIST_SET_INITIAL_SHUFFLE = 'PLAYLIST_SET_INITIAL_SHUFFLE';
export const PLAYLIST_CLEAR = 'PLAYLIST_CLEAR';

// displayStack
export const STACK_SET_SIDEBAR_VISIBLE = 'STACK_SET_SIDEBAR_VISIBLE';
export const STACK_SET_STACK_FOCUSED = 'STACK_SET_STACK_FOCUSED';
export const STACK_SET_POPUP_VISIBLE_OPTIONS_SIDEBAR =
  'STACK_SET_POPUP_VISIBLE_OPTIONS_SIDEBAR';
export const STACK_SET_POPUP_VISIBLE_OPTIONS_STACK =
  'STACK_SET_POPUP_VISIBLE_OPTIONS_STACK';
export const STACK_SET_POPUP_VISIBLE_STACK_CREATE =
  'STACK_SET_POPUP_VISIBLE_STACK_CREATE';
export const STACK_SET_POPUP_VISIBLE_STACK_EDIT =
  'STACK_SET_POPUP_VISIBLE_STACK_EDIT';
export const STACK_CLEAR = 'STACK_CLEAR';
