// session
export const SESSION_SET_AUTHENTICATED = 'SESSION_SET_AUTHENTICATED';
export const SESSION_SET_UNAUTHENTICATED = 'SESSION_SET_UNAUTHENTICATED';
export const SESSION_SET_DISPLAY = 'SESSION_SET_DISPLAY';

// data
export const DATA_SET_STACKS = 'DATA_SET_STACKS';
export const DATA_SET_BLOCKS = 'DATA_SET_BLOCKS';

// displayPlaylist
export const PLAYLIST_SET_MODE = 'PLAYLIST_SET_MODE';
export const PLAYLIST_SET_PLAYLIST_STACK = 'PLAYLIST_SET_PLAYLIST_STACK';
export const PLAYLIST_SET_FOCUS_INITIAL = 'PLAYLIST_SET_FOCUS_INITIAL';
export const PLAYLIST_SET_FOCUS_FINISHED = 'PLAYLIST_SET_FOCUS_FINISHED';
export const PLAYLIST_SET_FOCUS_REMAINING = 'PLAYLIST_SET_FOCUS_REMAINING';
export const PLAYLIST_SET_FOCUS_CURRENT = 'PLAYLIST_SET_FOCUS_CURRENT';
export const PLAYLIST_ADD_COMPLETED_BLOCKS = 'PLAYLIST_ADD_COMPLETED_BLOCKS';
export const PLAYLIST_CLEAR_COMPLETED_BLOCKS = 'PLAYLIST_CLEAR_COMPLETED_BLOCKS';

// displayStack
export const STACK_SET_SIDEBAR_VISIBLE = 'STACK_SET_SIDEBAR_VISIBLE';
export const STACK_SET_STACK_FOCUSED = 'STACK_SET_STACK_FOCUSED';
export const STACK_SET_POPUP_VISIBLE_OPTIONS_SIDEBAR = 'STACK_SET_POPUP_VISIBLE_OPTIONS_SIDEBAR';
export const STACK_SET_POPUP_VISIBLE_OPTIONS_STACK = 'STACK_SET_POPUP_VISIBLE_OPTIONS_STACK';
export const STACK_SET_POPUP_VISIBLE_CREATE_STACK = 'STACK_SET_POPUP_VISIBLE_CREATE_STACK';
export const STACK_SET_POPUP_VISIBLE_EDIT_STACK = 'STACK_SET_POPUP_VISIBLE_EDIT_STACK';
